### ISSUE TITLE
PyPI

### ISSUE THREAD

**Issue by jayvdb** [m8r0wn/pymeta#3]
I'd like to be able to use this as part of a Python library I am building, but it appears this is not yet on PyPI.

https://pypi.org/project/PyMeta/ is unfortunately already taken.

**Comment by m8r0wn** [comment]
Hey @jayvdb,

I noticed that as well, the name PyMeta was already taken :/ Given the tool is a rewrite of PowerMeta in PS1 I am hesitant to change the name. Definitely interested in adding it to PyPi though. Would love to see it included in other projects. 

Ill keep looking into this and get going on a setup.py script!

**Comment by jayvdb** [comment]
The name `PowerMeta` is available on PyPI, or maybe `PyPowerMeta` ? ;-)  That would be confusing with https://pypi.org/project/PYPOWER/ .

The clash between pymeta's will mean pip will overwrite one with the other if they are both installed at the same time, but that isnt a likely scenario.

But a way to avoid that is to install into a directory name other than `pymeta`, and then have a entry script called `pymeta`.

The [other pymeta](https://bazaar.launchpad.net/~washort/pymeta/trunk/files) doesn't have a bin script called `pymeta`, so there will not be a clash.

**Comment by m8r0wn** [comment]
The various ways to capitalize ```pymeta``` were taken and the most sensible option left was ```pymetadata```. However, I can confirm ```pip3 install pymetadata``` is working!

Once installed you can reference either ```pymeta``` or ```pymetadata``` from the command line. Hopefully, this wont cause any name clashes, but well address them as they pop up ;) Another cool thing we did was include a Unix binary of ExifTool so it no longer needs to be installed with a bash setup file.

In your original message you mentioned using it as part of a Python library, just a heads up, I should have another commit coming soon that refreshes the original code and may make that easier. The code restructuring for this issue turned up a few things ill be updating.

Thanks again for your help!
\-m8r0wn
